import Head from 'next/head'
import Image from 'next/image'
import Body from '../components/Body'
import Header from '../components/Header'

export default function Home({ data }) {
  console.log(data);
  return (
    <div className="h-full flex-column">
      <Head>
        <title>Edvora ride</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Body data={data} />
    </div>
  )
};

export async function getServerSideProps() {
  const res = await fetch(`https://assessment.api.vweb.app/rides`)
  const data = await res.json()
  return { props: { data } }
}
